env:
  TERM: xterm-256color
font:
  normal:
    family: Hack NF
    style: Regular
  size: 9
background_opacity: 0.85
window:
  startup_mode: Maximized
  decoration: none
  padding:
    x: 0
    y: 0
draw_bold_text_with_bright_colors: true
selection:
  save_to_clipboard: true
cursor:
  style: Beam
key_bindings:
 - { key: V,        mods: Control|Shift, action: Paste            }
 - { key: Insert,   mods: Shift,         action: PasteSelection   }
 - { key: C,        mods: Control|Shift, action: Copy             }
 - { key: Key0,     mods: Control,       action: ResetFontSize    }
 - { key: Equals,   mods: Control,       action: IncreaseFontSize }
 - { key: Add,      mods: Control,       action: IncreaseFontSize }
 - { key: Subtract, mods: Control,       action: DecreaseFontSize }
 - { key: Minus,    mods: Control,       action: DecreaseFontSize }
 - { key: T,        mods: Control,       action: SpawnNewInstance }
 - { key: F,        mods: Control,       action: ToggleFullscreen }
 - { key: M,        mods: Control,       action: Minimize         }
mouse_bindings:
 - { mouse: Right, action: Paste }
 - { mouse: Middle, action: PasteSelection }
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#eaeaea'
    dim_foreground: '#9a9a9a'
    bright_foreground: '#ffffff'
  cursor:
    text: '#000000'
    cursor: '#ffffff'
  normal:
    black:   '#000000'
    red:     '#d54e53'
    green:   '#4e9a06'
    yellow:  '#e6c547'
    blue:    '#3781Da'
    magenta: '#c397d8'
    cyan:    '#70c0ba'
    white:   '#eaeaea'
  bright:
    black:   '#666666'
    red:     '#ff3334'
    green:   '#8ae234'
    yellow:  '#e7c547'
    blue:    '#7aa6da'
    magenta: '#b77ee0'
    cyan:    '#54ced6'
    white:   '#ffffff'
