env:
  TERM: xterm-256color
font:
  normal:
    family: Hack NF
    style: Regular
  size: 9
background_opacity: 0.75
window:
  startup_mode: Maximized
  decoration: none
  padding:
    x: 0
    y: 0
draw_bold_text_with_bright_colors: true
selection:
  save_to_clipboard: true
cursor:
  style: Beam
key_bindings:
 - { key: V,        mods: Control|Shift, action: Paste            }
 - { key: C,        mods: Control|Shift, action: Copy             }
 - { key: Insert,   mods: Shift,         action: PasteSelection   }
 - { key: Key0,     mods: Control,       action: ResetFontSize    }
 - { key: Equals,   mods: Control,       action: IncreaseFontSize }
 - { key: Add,      mods: Control,       action: IncreaseFontSize }
 - { key: Subtract, mods: Control,       action: DecreaseFontSize }
 - { key: Minus,    mods: Control,       action: DecreaseFontSize }
 - { key: T,        mods: Control,       action: SpawnNewInstance }
 - { key: F,        mods: Control,       action: ToggleFullscreen }